sudo: required
dist: trusty
language: node_js
node_js:
  - '8'
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm run apply:trcpay
# after_success:
#   - npm run exec:coveralls
